### ISSUE TITLE
New installation/flashing method: CWM/TWRP flashable zips

### ISSUE THREAD

**Issue by ata2001** [postmarketOS/pmbootstrap#109]
I'm working on implementing support for creating android recovery-flashable zips in pmbootstrap.

### Why?
There are several reasons, why this would be useful, these are the ones, I find the most important.
* It would allow end users to install postmarketOS on their devices without an external GNU/linux (or any) computer.
* fastboot/heimdall(odin) access is often problematic with android devices, even after unlocking the bootloader.

### How?
There's a file in android update zips called update-binary, what gets executed by the recovery with superuser permissions. I've realized, we can put a simple shell script in the place of that binary, so there's no need to compile that from the android sources.

The zip will contain the whole rootfs unencrypted, and the dynamic binaries necessary for encryption/installation.
The script will extract the needed binaries to /tmp/, encrypt (in case full disc encryption is enabled) and format the partition, mount it and copy the system files over.

When we'll have a touch-friendly framebuffer input method (see #59), that is going to be used to input the password.

There are two commands/options/arguments I plan to add to pmbootstrap:
* `pmbootstrap install --android-recovery-zip` Generate a zip file for flashing with CWM compatible recoveries.
* `pmbootstrap flasher sideload` Flash the zip using adb's sideload feature.

### Current progress
I've made some progress with the installer script, it is now able to install the rootfs to the system partition, and handle full disk encryption.

You can find the scripts [here](https://github.com/ata2001/android-recovery-zip).

The most important files:

https://github.com/ata2001/android-recovery-zip/blob/master/bin/pmos_install

https://github.com/ata2001/android-recovery-zip/blob/master/bin/pmos_install_functions

https://github.com/ata2001/android-recovery-zip/blob/master/bin/pmos_setpw

Instructions for creating a flashable zip for your device:

https://github.com/ata2001/android-recovery-zip/blob/master/README.md

### Issues/Hacks
* The recovery looks for the executable named META-INF/com/google/android/update-binary. Replacing that binary with a shell script works fine, as mentioned above. However I think the name `update-binary` is a bit confusing. So I moved the main install script to a different path, and put a [simple script](https://github.com/ata2001/android-recovery-zip/blob/master/META-INF/com/google/android/update-binary), that extracts and calls `pmos_install` in its place.

* Since zip doesn't support every attribute needed for the rootfs, we need to include a tar.gz archive inside the zip. (TWRP has no support for tar.gz archives, see https://github.com/TeamWin/Team-Win-Recovery-Project/issues/473) This may cause problems on devices with less memory.

* Setting LD_LIBRARY_PATH has no effect, cryptsetup won't run unless the .so files are in /lib/. A workaround is to create symlinks. https://github.com/ata2001/android-recovery-zip/blob/master/bin/pmos_install#L17-L21

@ollieparanoid about the issue on Matrix:
> there are other methods. you could patch the binaries with lddpatcher or how it is called looking it up and you could instead of directly calling the binaries execute the interpreting so file also looking it up with another library path as argument. I've done such hacks as I've tried to package cross-compilers from other distros in a very early stage, before I could get the Alpine cross-compilers working properly

>  "patchelf" is the program that allows you to edit the binaries to use another so path. but I think it won't work on arm (so it's useless for your case!). it is packaged for alpine, here's the homepage: https://nixos.org/patchelf.html
/lib/ld-musl-x86_64.so.1 is the program, that executes all dynamic executables. you can pass paths there. but you would need a wrapper for all binaries, that you need to call, so this also isn't a nice solution

He also suggested using a chroot.

* `pmos_setpw` needs input from an interactive shell. That might not be possible in some recoveries. TWRP users can use the built-in terminal or `adb shell`.

### Todo
- [x] Flash boot partition too
- [x] Install without full disk encryption
- [x] SD card install
- [x] Custom cipher
- [x] Integrate into pmbootstrap
- [x] Isorec flashing
- [ ] Verify device codename

**Comment by ollieparanoid** [comment]
Sounds good! A few recommendations:
* Make sure, that you compile all binaries, that you ship yourself, statically.
* (You could use Alpine's `busybox-static` package, if you need it)
* I recommend setting the password from withing the recovery. You could set it via telnet for now (like in the initfs), and when we have a framebuffer on screen keyboard (#59), we could use that instead (in the future)

**Comment by ata2001** [comment]
@ollieparanoid Added explanations, would --recovery_zip be better?

**Comment by MartijnBraam** [comment]
I think `--android-update-zip`

**Comment by ollieparanoid** [comment]
Ah, `adb sideload` could do that? Nice! I'd also call it `--android-(something)-zip`, maybe `--android-zip`, because it is Android specific and pmOS doesn't only run on Android.

**Comment by PabloCastellano** [comment]
I've started working on it and made some progress:

http://imgur.com/a/c2uUO

Looks like it works but cannot really test it because of https://github.com/postmarketOS/pmbootstrap/issues/126

**Comment by ollieparanoid** [comment]
We have a `pmbootstrap flasher export` command now.
I suggest adding the zip export like this:
* Command line: `pmbootstrap flasher export --android-recovery-zip`
* This builds the zip file in the native chroot (only, because `--android-recovery-zip` is specified), and exports it as symlink to the target folder (just like the other files get exported in "flasher export")

Relevant file: [`export.py`](https://github.com/postmarketOS/pmbootstrap/blob/master/pmb/flasher/export.py)

**Comment by drebrez** [comment]
I'm considering to have a command like `pmbootstrap flasher export --odin-zip` which creates an Odin flashable file for samsung devices.
I need to figure out if it's possible to flash system partitions but for the kernel/initramfs partitions it works well.
The only drawback of using Odin is that it will increment the flash counter and void the warranty. Not sure if we have to consider that.

**Comment by ata2001** [comment]
Made an update to the original post.

**Comment by ollieparanoid** [comment]
Great progress and documentation! :+1:

**Comment by drebrez** [comment]
@ata2001 I'm going to test it very soon, good job.

You considered also writing the kernel/initramfs partitions?

**Comment by ata2001** [comment]
@drebrez Thank you!

Yes, if it's feasible on a device, then we could do that from the recovery too.

Be careful when you test it! Read the scripts beforehand! I've only tried it on amami.

**Comment by tssk** [comment]
@ata2001 Hello, I tried this to create ZIP for i9100 but it failed for me:

(026297) [00:25:15] (buildroot_armhf) create recovery zip
(026297) [00:25:15] (buildroot_armhf) % cd /var/lib/postmarketos-android-recovery-installer/ && mv /tmp/install_options install_options
(026297) [00:25:15] (buildroot_armhf) % cd /var/lib/postmarketos-android-recovery-installer/ && cp /mnt/rootfs_samsung-i9100/boot/boot.img-samsung-i9100 boot.img
cp: can't stat '/mnt/rootfs_samsung-i9100/boot/boot.img-samsung-i9100': No such file or directory
(026297) [00:25:15] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(026297) [00:25:15] NOTE: The failed command's output is above the ^^^ line in the logfile: /home/safarik/.local/var/pmbootstrap/log.txt
(026297) [00:25:15] ERROR: Command failed: (buildroot_armhf) % cd /var/lib/postmarketos-android-recovery-installer/ && cp /mnt/rootfs_samsung-i9100/boot/boot.img-samsung-i9100 boot.img

Is there something that I can make to get it work?

Thanks

**Comment by drebrez** [comment]
@ata2001 any plan for supporting the isorec devices?

**Comment by ata2001** [comment]
@drebrez I will do it, but testing it on real samsung devices would be a really big help.

**Comment by drebrez** [comment]
@ata2001 ok, ping me in chat if you need some info about this "isorec" style and let me know when you have something I can test 👍
