### ISSUE TITLE
Only create the initramfs when necessary

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#411]
Right now we create the initramfs whenever it could be necessary (simply to avoid running an old version, which is really annoying for development, and because it introduces bugs all the time).

It depends on a lot of factors, when one of those changes we should rebuild the initramfs:
* installed kernel (with the flavor for which we want to generate the initramfs)
* device package
* postmarketos-splash
* postmarketos-mkinitfs
* initramfs hooks changed/got updated

Maybe we should save a file with all versions of the last generated initramfs, and compare that file with the last one to decide if a rebuild is necessary. Note that generating the initramfs is done in the chroot, and must work completely independent of pmbootstrap (so we can update it once it is installed on the device with the package manager).

**Comment by ollieparanoid** [comment]
FYI, if someone is annoyed by this, use `pmbootstrap -s` to skip initramfs generation during the current `pmbootstrap` run.

**Comment by ollieparanoid** [comment]
@drebrez asked me to create a bunch of checkboxes for an initial version, that caches the splashes and assign him to this ticket.

**TODO (cache splashes):**
- [ ] Write new splash screens to this path first: `/var/cache/postmarketos-mkinitfs/splashes/splash_$hash.ppm.gz` (quickly made up file name, please reconsider if that really makes sense). $hash would be a hash of the postmarketos-splash version, the config file, the device resolution and the text to be displayed
- [ ] Only generate a new splash screen, when that output file does not exist.
- [ ] Put the splash into the initramfs as usually (but from that location instead of from some temp path)
- [ ] When a new splash has been generated, delete the whole cache folder. Usually we would need to rebuild all splashes in one go anyway, and that way we don't have left-overs.

**TODO (only build if necessary):**
- [ ] Create a list of files related to the initramfs (either the ones that get included, or the ones that help generating it) at the beginning of mkinitfs.sh, together with the last modified timestamp of those files (`ls` is good enough)
- [ ] Put that information into a temporary file and hash it
- [ ] Compare that hash against the last file list hash (stored in `/var/cache/postmarketos-mkinitfs/` somewhere)
- [ ] if there is no old file list hash, or no old initramfs file, or the hash differs, build a new initramfs. otherwise, do nothing.
- [ ] save the current file list hash in that cache folder

**Comment by ollieparanoid** [comment]
As discussed in #796 this issue is mostly dealt with, however we can spare a few more seconds by not only caching the splash screens and `initramfs-extra`, but also the regular `initramfs`.
