### ISSUE TITLE
Package msm framebuffer refresher

### ISSUE THREAD

**Issue by ollieparanoid** [postmarketOS/pmbootstrap#584]
@drebrez found this:
https://github.com/AsteroidOS/msm-fb-refresher

Some context: we have noticed, that some framebuffer drivers from Android kernels only implement double-buffering, but not single-buffering. weston, fbsplash and probably a lot of other Linux programs assume, that the single-buffering is working.

Right now we have a `while true` shell-script, that forces the refresh all the time. The `msm-fb-refresher` does basically the same thing, but more elegantly by only calling the necessary kernel syscall and - most importantly - with a sleep between the calls instead of running just all the time.

**TODO:**
* [x] package `msm-fb-refresher`
* [x] add a new deviceinfo option, that enables this hack
* [x] extend the mkinitfs code to put msm-fb-refresher into the initramfs, in case that option is set
* [x] extend the init script to actually run it, if it exists
* [ ] enable the option in all devices, that require the while true hack right now, and depend on the msm-fb-refresher package. also remove the existing while true hack.

**Comment by craftyguy** [comment]
Unless I'm missing something, #587 implements the first 4 items on that list. I've updated the pmOS wiki to mention the new deviceinfo var for toggling this (`deviceinfo_msm_refresher`).

**Comment by montvid** [comment]
There is another one here: [https://github.com/crondog/arch-flo/blob/master/refresher.c](https://github.com/crondog/arch-flo/blob/master/refresher.c) Is it any better?

**Comment by ollieparanoid** [comment]
Thanks for the link @montvid! I've compared the code, and while it is different, it is written differently, it is essentially doing the same thing:

```c
struct fb_var_screeninfo var;
int fd = open("/dev/fb0", O_RDWR);
ioctl(fd, FBIOGET_VSCREENINFO, &var);
while(1) {
    ioctl(fd, FBIOPAN_DISPLAY, &var);
    usleep(16666);
}
```
So I assume that it behaves the same way (not tested though).

**Comment by drebrez** [comment]
Seems that only `device-lg-lenok` still uses the `while echo '0,0' >  pan` workaround, @JamesHealdUK do you have time to test the `msm-fb-refreshed` on the LG Lenok?

**Comment by ollieparanoid** [comment]
We have packaged it successfully, and quite a few devices are using it now. For some devices it does not work (causing reboots), but we have issue #604 for that. Closing.
